[package]
name = "ts3status-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cached = { version = "0.56.0", features = ["async"] }
chrono = "0.4.43"
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.228"
ts3 = "0.4.1"
rusqlite = { version = "0.38.0", features = ["bundled"] }
itertools = "0.14.0"
figment = { version = "0.10", features = ["toml", "env"] }
